#define S \
	"LONGLONGLONGLONGLONGLONGLONGLONG" \
	"LONGLONGLONGLONGLONGLONGLONGLONG" \
	"LONGLONGLONGLONGLONGLONGLONGLONG" \
	"LONGLONGLONGLONGLONGLONGLONGLONG" \
	"LONGLONGLONGLONGLONGLONGLONGLONG" \
	"LONGLONGLONGLONGLONGLONGLONGLONG" \
	"LONGLONGLONGLONGLONGLONGLONGLONG" \
	"LONGLONGLONGLONGLONGLONGLONGLONG" \
	"STRING"
