#define S \
	"LONGLONGLONGLONGLONGLONGLONGLONG" \
	"LONGLONGLONGLONGLONGLONGLONGLONG" \
	"LONGLONGLONGLONGLONGLONGLONGLONG" \
	"LONGLONGLONGLONGLONGLONGLONGLONG" \
	"LONGLONGLONGLONGLONGLONGLONGLONG" \
	"LONGLONGLONGLONGLONGLONGLONGLONG" \
	"LONGLONGLONGLONGLONGLONGLONGLONG" \
	"LONGLONGLONGLONGLONGLONGLONGLONG" \
	"STRING"

#define W \
	L"ONGLONGLONGLONGLONGLONGLONGLONG" \
	"LONGLONGLONGLONGLONGLONGLONGLONG" \
	"LONGLONGLONGLONGLONGLONGLONGLONG" \
	"LONGLONGLONGLONGLONGLONGLONGLONG" \
	"LONGLONGLONGLONGLONGLONGLONGLONG" \
	"LONGLONGLONGLONGLONGLONGLONGLONG" \
	"LONGLONGLONGLONGLONGLONGLONGLONG" \
	"LONGLONGLONGLONGLONGLONGLONGLONG" \
	"WIDESTRING"
