#define ALIGNED(x) __attribute__((aligned(x)))
#define ALLOC_SIZE(argnum) __attribute__((alloc_size(argnum)))
#define DEPRECATED(msg) __attribute__((deprecated(msg)))
#define FORMAT(fmtarg, firstvararg) __attribute__((format(__printf__, fmtarg, firstvararg)))
#define FORMAT_ARG(fmtarg) __attribute__((format_arg(fmtarg)))
#define NONNULL(x) __attribute__((nonnull(x)))
#define OPTIMIZE(x) __attribute__((optimize(x)))
#define SECTION(x) __attribute__((section(x)))
#define VISIBILITY(x) __attribute__((visibility(x)))
